### ISSUE TITLE
ch7 7.3 String Manipulation

### ISSUE THREAD

**Issue by GengBin414** [wesm/pydata-book#92] opened 2018-07-05 03:23 UTC
Vectorized String Functions in pandas

I can't figure out the meaning of the following code, can you explain it further: 

In [176]: matches .str.get(1)
Out[176]:
Dave NaN
Rob NaN
Steve NaN
Wes NaN
dtype: float64

In [177]: matches .str[0]
Out[177]:
Dave NaN
Rob NaN
Steve NaN
Wes NaN
dtype: float64

**Comment by wesm** [comment] 2018-07-05 21:11
Looks like errata; I'm about to do some corrections of errata so I'll let you know when I get to this one

**Comment by GengBin414** [comment] 2018-07-06 02:30
Thanks for your prompt reply!

**Comment by wesm** [comment] 2018-08-28 02:01
This will be fixed in the next printing

**Comment by Wendy-mhwu** [comment] 2020-03-02 06:56
Has it been changed? My second edition book is still this, I can't figure out, it gave error message.

**Comment by wesm** [comment] 2020-03-02 21:47
Reopening until I can confirm this is resolved and also fixed in the notebooks here

**Comment by KXCY-AI** [comment] 2021-04-13 11:21
Got the same error output, and waiting for the way to walk around.

**Comment by wesm** [comment] 2021-11-21 23:38
Will be fixed in the 3rd edition (notebooks will be updated in this repo when it's closer to publication)

**Closed as completed by wesm** 2021-11-21 23:38 UTC
